[package]
name = "moa_quizz"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
angle_calculation = { path = "../angle_calculation" }
rand = "0.8"
